//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.WebFresher062023.Demo.Domain.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.WebFresher062023.Demo.Domain.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HM/KH lũy kế.
        /// </summary>
        public static string AccumulatedDepreciation {
            get {
                return ResourceManager.GetString("AccumulatedDepreciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại tài sản.
        /// </summary>
        public static string AssetCategoryCode {
            get {
                return ResourceManager.GetString("AssetCategoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID loại tài sản.
        /// </summary>
        public static string AssetCategoryId {
            get {
                return ResourceManager.GetString("AssetCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên loại tài sản.
        /// </summary>
        public static string AssetCategoryName {
            get {
                return ResourceManager.GetString("AssetCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản.
        /// </summary>
        public static string AssetCode {
            get {
                return ResourceManager.GetString("AssetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản phải kết thúc bằng chữ số.
        /// </summary>
        public static string AssetCodeNotEndNumber {
            get {
                return ResourceManager.GetString("AssetCodeNotEndNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID tài sản.
        /// </summary>
        public static string AssetId {
            get {
                return ResourceManager.GetString("AssetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài sản.
        /// </summary>
        public static string AssetName {
            get {
                return ResourceManager.GetString("AssetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trùng mã tài sản.
        /// </summary>
        public static string ConflictAssetCode {
            get {
                return ResourceManager.GetString("ConflictAssetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyên giá.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00000000-0000-0000-0000-000000000000.
        /// </summary>
        public static string DefaultGuid {
            get {
                return ResourceManager.GetString("DefaultGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban.
        /// </summary>
        public static string DepartmentCode {
            get {
                return ResourceManager.GetString("DepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID phòng ban.
        /// </summary>
        public static string DepartmentId {
            get {
                return ResourceManager.GetString("DepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phòng ban.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỷ lệ hao mòn (%).
        /// </summary>
        public static string DepreciationRate {
            get {
                return ResourceManager.GetString("DepreciationRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trùng mã tài sản.
        /// </summary>
        public static string DuplicateAssetCodeInvalid {
            get {
                return ResourceManager.GetString("DuplicateAssetCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trùng mã chứng từ.
        /// </summary>
        public static string DuplicateIncreaseCode {
            get {
                return ResourceManager.GetString("DuplicateIncreaseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỷ lệ hao mòn phải bằng 1/số năm sử dụng.
        /// </summary>
        public static string EqualDepreciationRate {
            get {
                return ResourceManager.GetString("EqualDepreciationRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mật khẩu không đúng.
        /// </summary>
        public static string IncorrectUsernameOrPassword {
            get {
                return ResourceManager.GetString("IncorrectUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chứng từ.
        /// </summary>
        public static string IncreaseCode {
            get {
                return ResourceManager.GetString("IncreaseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chứng từ phải kết thúc bằng chữ số.
        /// </summary>
        public static string IncreaseCodeNotEndNumber {
            get {
                return ResourceManager.GetString("IncreaseCodeNotEndNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày chứng từ.
        /// </summary>
        public static string IncreaseDate {
            get {
                return ResourceManager.GetString("IncreaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày ghi tăng.
        /// </summary>
        public static string IncreaseRecordDate {
            get {
                return ResourceManager.GetString("IncreaseRecordDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phải kết thúc bằng chữ số.
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số năm sử dụng.
        /// </summary>
        public static string LifeTime {
            get {
                return ResourceManager.GetString("LifeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày chỉnh sửa.
        /// </summary>
        public static string ModifyDate {
            get {
                return ResourceManager.GetString("ModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm sản xuất.
        /// </summary>
        public static string ProductionYear {
            get {
                return ResourceManager.GetString("ProductionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mua.
        /// </summary>
        public static string PurchaseDate {
            get {
                return ResourceManager.GetString("PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mua phải nhỏ hơn ngày sử dụng.
        /// </summary>
        public static string PurchaseDateLessUsedDate {
            get {
                return ResourceManager.GetString("PurchaseDateLessUsedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị còn lại.
        /// </summary>
        public static string ResidualValue {
            get {
                return ResourceManager.GetString("ResidualValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng nguyên giá.
        /// </summary>
        public static string TotalCost {
            get {
                return ResourceManager.GetString("TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm bắt đầu theo dõi tài sản trên phần mềm.
        /// </summary>
        public static string TrackedYear {
            get {
                return ResourceManager.GetString("TrackedYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sử dụng.
        /// </summary>
        public static string UsedDate {
            get {
                return ResourceManager.GetString("UsedDate", resourceCulture);
            }
        }
    }
}
